"""add prompt management models

Revision ID: 9dc8f65303ca
Revises: 9407d8279ab9
Create Date: 2026-06-10 01:18:49.906553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc8f65303ca'
down_revision: Union[str, None] = '9407d8279ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_model', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompts_category'), 'ai_prompts', ['category'], unique=False)
    op.create_index(op.f('ix_ai_prompts_name'), 'ai_prompts', ['name'], unique=False)
    op.create_table('prompt_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_quiz_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_completion_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_response_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id')
    )
    op.add_column('ai_usage_logs', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.add_column('ai_usage_logs', sa.Column('prompt_version', sa.Integer(), nullable=True))
    op.add_column('ai_usage_logs', sa.Column('prompt_variant', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'ai_usage_logs', 'ai_prompts', ['prompt_id'], ['id'], ondelete='SET NULL')
    op.add_column('chat_sessions', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('prompt_version', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('prompt_variant', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'ai_prompts', ['prompt_id'], ['id'], ondelete='SET NULL')
    op.add_column('quizzes', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('prompt_version', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('prompt_variant', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'ai_prompts', ['prompt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'prompt_variant')
    op.drop_column('quizzes', 'prompt_version')
    op.drop_column('quizzes', 'prompt_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'prompt_variant')
    op.drop_column('chat_sessions', 'prompt_version')
    op.drop_column('chat_sessions', 'prompt_id')
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.drop_column('ai_usage_logs', 'prompt_variant')
    op.drop_column('ai_usage_logs', 'prompt_version')
    op.drop_column('ai_usage_logs', 'prompt_id')
    op.drop_table('prompt_metrics')
    op.drop_index(op.f('ix_ai_prompts_name'), table_name='ai_prompts')
    op.drop_index(op.f('ix_ai_prompts_category'), table_name='ai_prompts')
    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
